### ISSUE TITLE
七牛SDK 更新导致 持久化处理调用不兼容了

### ISSUE THREAD

**Issue by coderhwz** [itbdw/laravel-storage-qiniu#12]
当前调用： https://github.com/itbdw/laravel-storage-qiniu/blob/master/src/QiniuAdapter.php#L409

七牛SDK： https://github.com/qiniu/php-sdk/blob/master/src/Qiniu/Processing/PersistentFop.php#L52

悲剧了

**Comment by itbdw** [comment]
再试试呢。。。

**Comment by coderhwz** [comment]
好的，项目里七牛的SDK不是指定了版本号吗，理论上应该不会更新七牛SDK的才对
