### ISSUE TITLE
关于文件名的问题

### ISSUE THREAD

**Issue by z-perfe** [itbdw/laravel-storage-qiniu#9]
`$file_name = "image/14920494118326.jpg"  ;
$disk = Storage::disk('qiniu');
$disk->put( $file_name, $file );`

但在七牛云上传的文件变成了:	
image/14920494118326.jpg/SizBV1QpFzT3SxoJSjWvQHLMewcjNDaQsm1EHeTk.jpeg

是我在哪里出了问题?

**Comment by itbdw** [comment]
这个应该不会，你再调试一下呢，只是这段代码就成了这样了？

**Comment by itbdw** [comment]
没有复现，使用正常。
